### ISSUE TITLE
Publish on npm/bower

### ISSUE THREAD

**Issue by Remo** [gmaps-marker-clusterer/gmaps-marker-clusterer#2]
How shall we do this? The names are already taken? Should be rename everything to js-marker-clusterer-new?? I'd be open to a better idea ;-)

- [x] NPM: https://www.npmjs.com/package/gmaps-marker-clusterer
- [ ] Bower: Git tags neccessary

**Comment by XmlmXmlmX** [comment]
Or we rename it to gmaps-js-marker-clusterer.

**Comment by mnewmedia** [comment]
I'm not for `js-marker-clusterer-new` and using something like `js-marker-clusterer-2` sounds like version--like. What about:
- `google-maps-clusterer`
- `google-maps-cluster`
- `gmaps-clusterer`
- `gmaps-cluster`
- `gmaps-marker-clusterer`
- `gmaps-marker-cluster`

**Comment by Remo** [comment]
I just thought that keeping `js-marker-clusterer` in the name would make it more obvious to others that this repo is related to the original, but I agree, it sounds rather ugly. Personally I like `google-maps-clusterer` best, but I understand that lots of people can have different opinions..

**Comment by XmlmXmlmX** [comment]
The name should not differ too much for a better recognition value.

**Comment by XmlmXmlmX** [comment]
What about a scope for the package?

**Comment by Remo** [comment]
I tend agree with @XmlmXmlmX I just feel like `gmaps-js-marker-clusterer` is pretty long. Maybe meet in the middle and use `gmaps-marker-clusterer`?

**Comment by XmlmXmlmX** [comment]
@Remo That's it

**Comment by Remo** [comment]
okay, since it was also on the list of Pablo I'll rename everything, just a sec

**Comment by XmlmXmlmX** [comment]
Version 1.0.0 published at npmjs.com: https://www.npmjs.com/package/gmaps-marker-clusterer/

**Comment by XmlmXmlmX** [comment]
Tag [v1.0.0](https://github.com/gmaps-marker-clusterer/gmaps-marker-clusterer/releases/tag/v1.0.0) added to master branch. Bower package registered.
