### ISSUE TITLE
A bug in the documentation: styles property expects an array, not object.

### ISSUE THREAD

**Issue by wujekbogdan** [gmaps-marker-clusterer/gmaps-marker-clusterer#20]
This is a copy of [an issue reported in the old repository](https://github.com/googlemaps/js-marker-clusterer/issues/120#issuecomment-278871345). I was asked to post here.

The [documentation](https://googlemaps.github.io/js-marker-clusterer/docs/reference.html) says that `styles` property should be an object. But when an object is given then there's an error in the console:
```
TypeError: this.styles_.push is not a function
at MarkerClusterer.setupStyles_ (markerclusterer.js:249)
```
When a single element array that contains an object is given then it works fine and styles are applied.

**Comment by Remo** [comment]
I don't quite understand the code yet, `useStyle` looks a bit strange to me. However, instead of changing the documentation I tried to change the code https://github.com/gmaps-marker-clusterer/gmaps-marker-clusterer/issues/21. It's not completely tested, just an idea. I feel it would be more intuitive to use an object instead of an array, wouldn't it?

**Comment by Remo** [comment]
Maybe I got this completely wrong, maybe it's for the different cluster sizes, at least that's what I think when I look at this https://googlemaps.github.io/js-marker-clusterer/examples/advanced_example.html Maybe it is a documentation issue and should really be a list (array) of styles.

**Comment by wujekbogdan** [comment]
> I feel it would be more intuitive to use an object instead of an array, wouldn't it?

Yes. For me, it should be an object. I see no point in passing an array.

**Comment by Remo** [comment]
@wujekbogdan it has to be an array as we can specify cluster icons for multiple cluster sizes. The advanced examples shows this. I didn't change any code, just the type hint and the documentation.
Thanks for reporting this!

**Comment by nirpan** [comment]
This needs updating in the documentation as it is still showing the 'styles' options as an Object and not an array as it should be.

**Comment by Remo** [comment]
@nirpan where are you looking? it's an array here https://gmaps-marker-clusterer.github.io/gmaps-marker-clusterer/

**Comment by nirpan** [comment]
> @nirpan where are you looking? it's an array here https://gmaps-marker-clusterer.github.io/gmaps-marker-clusterer/

Oh my bad! I should have RTFM but google showed the archived repo much higher in the search result and I was looking at this page: https://googlemaps.github.io/js-marker-clusterer/docs/reference.html

**Comment by Remo** [comment]
yes, that one is from google. We are just a fork. Nothing we can do about that.
