### ISSUE TITLE
Cluster css classes based on cluster range. 

### ISSUE THREAD

**Issue by vorbe** [gmaps-marker-clusterer/gmaps-marker-clusterer#35]
Is it possible to add additional classes to the cluster pin based on a cluster size range that mirrors the way images are being used in the advanced example?

https://gmaps-marker-clusterer.github.io/gmaps-marker-clusterer/advanced-example/ 

It seems like all the images for the various representations of these ranges (e.g from m1.png through to m5) have been added inline so there's no easy way to try and mimic this with a css only approach if we were going for something basic like a simple circle or something that's shown in the custom-pin example.

**Comment by XmlmXmlmX** [comment]
Hi, thank you for your idea.

There are already classes for each cluster-range. See [here](https://github.com/gmaps-marker-clusterer/gmaps-marker-clusterer/blob/master/src/markerclusterer.js#L1188-L1192). By default these classnames will be rendered like this: `.cluster1`, `.cluster2`, `.cluster3`, `.cluster4`, `.cluster5`.

Is that what you have expected?

**Comment by vorbe** [comment]
Thanks for your reply.

That was what I was looking for, looks like I might have been too far zoomed out to recognize the cluster classes being unique!
