### ISSUE TITLE
Documentation: Please add a note about the repaint method and using it when your markers change position frequently

### ISSUE THREAD

**Issue by rognstad** [gmaps-marker-clusterer/gmaps-marker-clusterer#38]
I think the new documentation looks much nicer! Would you please add a note about the repaint method? It's very useful for maps that have moving markers (e.g. vehicles). Calling resetViewport() and redraw() works, but causes the clusters to flicker during each update. repaint() largely avoids this (and can probably totally do so if someone uses cluster images without transparency).

**Comment by Remo** [comment]
Thanks! It might be faster if you create a pull request for it ;-)
It's all here https://github.com/gmaps-marker-clusterer/gmaps-marker-clusterer/tree/gh-pages

**Comment by rognstad** [comment]
Sure, I should have just done that in the first place. 😄 

Also, here's a link to an old Google Groups discussion from when the method was originally added: https://groups.google.com/forum/#!topic/google-maps-js-api-v3/kspTUjVcFsY That's how I realized it could help with frequently moving markers. I meant to include that originally.

**Comment by Remo** [comment]
thanks
