### ISSUE TITLE
Support rendering custom HTML for clusters or allow custom cluster draw and onAdd functions

### ISSUE THREAD

**Issue by rognstad** [gmaps-marker-clusterer/gmaps-marker-clusterer#41]
The custom CSS example is quite nice, but I'd like to customize the look of the clusters more substantially, which would require changing the ClusterIcon draw and onAdd methods.

Would you be open to a PR allowing those functions to be provided as options to the clusterer like onMouseoverCluster?

**Comment by Remo** [comment]
I never tried to customize anything beyond of what is shown in the example, can't judge whether this makes sense, but I guess it's fine as long as we don't break backward compatibility.

**Comment by Remo** [comment]
Added the new methods here https://github.com/gmaps-marker-clusterer/gmaps-marker-clusterer/commit/f3a471415ae566a9e78b91dd37c7396b04a62ed4

Going to close this as the second PR has been merged
