### ISSUE TITLE
showing the cluster location with polygon when user mouseover the cluster / marker

### ISSUE THREAD

**Issue by chaiwei** [gmaps-marker-clusterer/gmaps-marker-clusterer#47]
Hi, 

Is there any way we can do this  with gmaps marker clusterer?
It will show the polygon for the clustered area when user mouse over to that location
https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html

**Comment by Remo** [comment]
It probably doesn't have much to do with the marker-clusterer library. The MarkerCluster class extends google.maps.OverlayView and thus allows you to use all the events available there. Painting polygons has also not much to do with clusters. I don't have an example around as I never had that requirement, but I don't see why it shouldn't be possible. It won't be part of the clusterer library though, it's a specific case you'll have to deal with yourself.
