### ISSUE TITLE
Clusters and not clickable on Microsoft Edge.

### ISSUE THREAD

**Issue by hassam7** [gmaps-marker-clusterer/gmaps-marker-clusterer#49]
I am using latest version of MarkerClusterer. I have set svg as a markercluster icon and I am not able to click on it. It does not work.

**Comment by Remo** [comment]
Do you have an online example where we can see the problem?

**Comment by hassam7** [comment]
@Remo thanks for the reply. Turns out that I can not reproduce this issue on plnkr which lets me to conclude that problem is with my code and not gmaps-marker-clusterer. I will investigate further and If issue is due to gmaps-marker-clusterer will reopen the ticket.

Kind Regards
