### ISSUE TITLE
setting cssClass results in no markers displayed

### ISSUE THREAD

**Issue by barryceelen** [gmaps-marker-clusterer/gmaps-marker-clusterer#52]
When I define the `cssClass` option, no cluster markers are rendered?

(According to the documentation the `cssClass` should be set in the `styles` option. Looking at the source it expects the cssClass value in the options object.)

```
var opts = {
        styles: [{
          'url': 'http://example.com/example.png',
          'height': 40,
          'width': 40,
          'anchor': [0,0],
          'textColor': '#fff',
          'textSize': 12,
          'backgroundPosition': '0,0'
        }],
        cssClass: 'my-cool-css-class',
        zoomOnClick: true
      };
```

**Comment by Remo** [comment]
Is there a JavaScript error or any other hint that might help?

**Comment by barryceelen** [comment]
Ah no, wait. The markers are rendered when I add the `cssClass` option, but are all placed in the top left corner of the map. Leaving out the `cssClass` option renders them in the correct location.
I must be missing something here?

**Comment by Remo** [comment]
Got an link for me so that I can see it myself?

**Comment by barryceelen** [comment]
@Remo Got it. The custom class needs `position: absolute` defined to make it work. The example in the readme file does have this. Sorry for wasting your time!

**Comment by Remo** [comment]
No worries, thanks for the PR, will check later!
